### PR TITLE
Memory usage optimization

### PR DESCRIPTION
**Pull request by dbenninger**
We are using Clara in a larger Vaadin project and noticed that it allocates a lot of memory. Using a profiler, we were able to narrow it down to the findMethods call in the AttributeHandler. The problem is String.matches():

screen shot 2015-12-08 at 18 12 11

Looking at the code in AttributeHandler, we do not really need to use regex at that point, so I have introduced a new method. It seems to work fine and uses a lot less memory:

screen shot 2015-12-08 at 18 37 32

[Review on Reviewable](https://reviewable.io/reviews/tehapo/clara/39)

### CODE REVIEW

**Comment by tehapo** [comment]
Thanks, this looks great! I will try out the code, merge the PR and make a new release later this week.

**Comment by tehapo** [comment]
Reviewed your PR and it looks ok, but I started wondering if a smaller change would do the same trick.

https://github.com/tehapo/Clara/tree/optimize
Could you checkout this branch and profile if this change alone would improve the memory usage for your large application? For some reason the test case in your commit gave pretty random results for me.

https://github.com/tehapo/Clara/commit/963f74716150195127e21fc79d298a24d8b40234
In this change I moved the creation of `Pattern` and `Matcher` instances outside the loop. And also as another optimization, I now check the parameter count before the regex comparison.

**Comment by dbenninger** [comment]
Your change is definitely smaller and does not lead to duplicated code and the effect seems to be the same:

screen shot 2015-12-14 at 10 14 49

Yes, the test case is unpredictable because the GC can kick in....

**Comment by tehapo** [comment]
Thanks for testing this out, I really appreciate the effort! :+1: 

I will merge my change to master branch and make a new release of Clara.

**Comment by dbenninger** [comment]
Great, thank you!

**Comment by tehapo** [comment]
Replaced by https://github.com/tehapo/Clara/pull/40.

**Comment by tehapo** [comment]
Clara version 1.4.2 now available from [Directory](https://vaadin.com/addon/clara) and Maven repository.

**Pull request closed without merging**
