### PR TITLE
make listener binding serializable

### PR DESCRIPTION
**Pull request by kumm**
Now session serialization works with clara when controllers are serializable.

### CODE REVIEW

**Comment by mrotteveel** [comment]
It would be nice if this could be merged and released. We have uptime requirements that will probably require us to have one node fail-over to another node, and session serialization is needed for that.

**Comment by mrotteveel** [comment]
This would fix issue #23

**Comment by tehapo** [comment]
Sorry, this one has been left hanging without any action. I'll look into this PR this later this week.

**Comment by mrotteveel** [comment]
No problem. I have another itch to scratch in this area (handling/unwrapping `InvocationTargetException` on `invoke`); I'll prepare another pull request when this has been merged.

**Pull request merged**
